# A Short introduction to Julia

## Variables, Numbers, and Strings

linguaggio semplice, unisce un po' C e python, è relativamente veloce con una sintassi simile a python

fornisce tool per calcolo scientifico e data science

ML meno sviluppato

julia è compilato just in time, usa LVM dietro le quinte


Variables do not need to be declared

In [1]:
x = 3

3

but the value they are *bound to* has a type

In [2]:
typeof(x)

Int64

We can re-assign ```x``` to another value of a different type

In [3]:
x = 3.4

3.4

In [6]:
typeof(x)

ComplexF64 (alias for Complex{Float64})

In addition to ```Int64``` (integers) and ```Float64``` (double-precision floating point), we also have others numeric types, like rational and complex numbers:

se si lavora solo con razionali si può avere la precisione

In [7]:
x = 3//4
typeof(x)

Rational{Int64}

In [8]:
x = 4.1 + 3.4im
typeof(x)

ComplexF64 (alias for Complex{Float64})

The common operations works on all numerical types:

In [10]:
3//4 + 7//9

55//36

In [11]:
(4.2 + 3.4im)*(7 - 2im)

36.2 + 15.4im

Exponentiation works with ```^```:

In [12]:
2^10

1024

If we need integer division we can use $\div$ SUPPORTA UNICODE

In [13]:
13 ÷ 5

2

The reminder is, as in many other languages, ```%```:

In [ ]:
13 % 5
ξ = 2


2

### Characters and Strings

The ```Char``` type is a single UTF-8 character represented in the code by enclosing it in single quotes

In [16]:
'a'

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [17]:
'🐱'

'🐱': Unicode U+1F431 (category So: Symbol, other)

A string is a (finite) sequence of characters and they are represented in the code by enclosing it in either double quotes or triple double quotes. Strings can span multiple lines

In [18]:
"Hello World"

"Hello World"

In [19]:
"""Hello
World"""

"Hello\nWorld"

In [20]:
"""Hello "Cruel" World"""

"Hello \"Cruel\" World"

Strings can be concatenated with ```*``` (and not ```+``` like in other languages)

In [21]:
"Hello" * " " * "World"

"Hello World"

Strings can be interpolated by using ```$```:

In [22]:
x = 4
"The value of x is $x"

"The value of x is 4"

In [23]:
"The result of x + 3 is $(x + 3)"

"The result of x + 3 is 7"

Other kinds of Strings literals exists (e.g., binary, regular expressions):

In [24]:
b"binary values" # An array of unsigned 8 bits integers

13-element Base.CodeUnits{UInt8, String}:
 0x62
 0x69
 0x6e
 0x61
 0x72
 0x79
 0x20
 0x76
 0x61
 0x6c
 0x75
 0x65
 0x73

In [25]:
r"[a-z]+\s*" # A regular expression

r"[a-z]+\s*"

### Symbols

A special kind of type is the ```Symbol``` type:

In [26]:
Symbol("hello")

:hello

In [27]:
typeof(:foo)

Symbol

Symbols are *interned strings*. You can use them, for example, as keywords (no need to use a String), but they have many other uses.

Symbols should be familiar to people programming in Lisp.

## Array, Dictionaries, and Tuples

### Arrays

Arrays can be defined similary to languages like Python by encosing the values in square brackets

In [28]:
v = [2,4,6,8]

4-element Vector{Int64}:
 2
 4
 6
 8

A one dimensional array of ```Int64```.

We can obtain the type of the elements contained in an array with ```eltype```

In [29]:
eltype(v)

Int64

and the length of the array by using ```length```

In [30]:
length(v)

4

Arrays can be of mixed types (might not be the best for efficiency)

In [31]:
v2 = [1, 3.4, "Hello"]

3-element Vector{Any}:
 1
 3.4
  "Hello"

In Julia, array are by default indexed from ```1``` and not from ```0```

In [32]:
v[1]

2

In [33]:
v[length(v)]

8

We can actually use any starting index with the package ```OffsetArrays.jl```

We can also retrieve the first and last element of the array using ```begin``` and ```end``` as indexes:

In [34]:
v[begin]

2

In [35]:
v[end]

8

#### Slices and viewes

As with many modern languages, arrays can be sliced using the syntax ```start_index:end_index```

In [36]:
v[2:3]

2-element Vector{Int64}:
 4
 6

Slices can be assigned to variables. In that case a *copy* is made

In [37]:
w = v[2:3]

2-element Vector{Int64}:
 4
 6

In [38]:
w[1] = 0
v

4-element Vector{Int64}:
 2
 4
 6
 8

If we want to refer to the same underlying memory we use ```view```

In [39]:
z = @view v[2:3]

2-element view(::Vector{Int64}, 2:3) with eltype Int64:
 4
 6

In [52]:
z[1] = 0
v

4-element Vector{Int64}:
 4
 0
 4
 8

#### Broadcasting

We may want to assign the same value to an entire slice of an array.

However, this will give an error:

In [53]:
v[1:3] = 4

ArgumentError: ArgumentError: indexed assignment with a single value to possibly many locations is not supported; perhaps use broadcasting `.=` instead?

We can prepend ```.``` to assignements (and any function call) to "broadcast" a value:

In [54]:
v[1:3] .= 4
v

4-element Vector{Int64}:
 4
 4
 4
 8

In [43]:
v

4-element Vector{Int64}:
 4
 4
 4
 8

#### Multidimensional arrays

Julia supports multi-dimensional array. 

We can write them remembering the following rules:

- Arguments separated by semicolons ```;``` or newlines are vertically concatenated
- Arguments separated by spaces or tabs are horizontally concatenated

In [55]:
M = [0 1 0 0
     1 0 0 1
     0 0 1 1]

3×4 Matrix{Int64}:
 0  1  0  0
 1  0  0  1
 0  0  1  1

We can obtain the dimensions of a multi-dimensional array using the ```ndims``` function

In [45]:
ndims(M)

2

And the length of a specific dimension using the ```size``` function

In [46]:
size(M)

(3, 4)

Indexing is made by using all indexes, separated by commas, inside square brackets:

In [47]:
M[1,2]

1

Notice that multidimensional arrays and arrays-of-arrays are different!

In [48]:
M2 = [[0,1,0,0], [1,0,0,1], [0,0,1,1]]

3-element Vector{Vector{Int64}}:
 [0, 1, 0, 0]
 [1, 0, 0, 1]
 [0, 0, 1, 1]

As before, we can slice the arrays. This time along multiple dimensions:

In [49]:
M[1:2,2:4]

2×3 Matrix{Int64}:
 1  0  0
 0  0  1

In [50]:
M[2:3,:]

2×4 Matrix{Int64}:
 1  0  0  1
 0  0  1  1

In [51]:
M[:,2:4]

3×3 Matrix{Int64}:
 1  0  0
 0  0  1
 0  1  1

As before, we can create views of the array

In [ ]:
A = view(M, 2:3, 2:4)acterized by a death rate 
𝜇
 and birth ra
A[1,1] = 99

In [ ]:
M

And the shape of an array can be changed via the function ```reshape```:

In [ ]:
reshape(M, 4, 3)

In [ ]:
reshape(M, 2, 3, 2)

In [ ]:
zeros(2,4,3)

#### Array Comprehension

As with list comprehension in languages like Python, Julia also supports array comprehension

In [ ]:
squares = [i^2 for i ∈ 1:10]

In [ ]:
mult_table = [i * j for i ∈ 1:5, j ∈ 1:10]

### Dictionaries

Dictionaries represent maps from a set $K$ of keys to a set $V$ of values

In [56]:
d = Dict('a' => 1, 2 => "text", :foo => :bar)

Dict{Any, Any} with 3 entries:
  2    => "text"
  'a'  => 1
  :foo => :bar

Dictionaries can be indexed similarly to arrays

In [57]:
d['a']

1

Assignment for non existing keys is possible and will add the key to the dictionary

In [58]:
d['z'] = 26
d

Dict{Any, Any} with 4 entries:
  2    => "text"
  'a'  => 1
  :foo => :bar
  'z'  => 26

The keys and values of a dictionary can be obtained by using the functions ```keys``` and ```values```, respectively:

In [59]:
keys(d)

KeySet for a Dict{Any, Any} with 4 entries. Keys:
  2
  'a'
  :foo
  'z'

In [60]:
values(d)

ValueIterator for a Dict{Any, Any} with 4 entries. Values:
  "text"
  1
  :bar
  26

In [61]:
for k ∈ values(d)
    print(k)
end

text1bar26

### Tuples

Tuples are fixed-length containers that cannot be modified (i.e., they are immutable).

In [62]:
tuple = (1.2, 2, "hello")

(1.2, 2, "hello")

In [63]:
typeof(tuple)

Tuple{Float64, Int64, String}

Tuples are indexed starting from $1$, like arrays

In [64]:
tuple[1]

1.2

For tuples consisting of only one element remember the comma at the end:

In [65]:
small_tuple = (3,)

(3,)

When created, tuples can also be *named*

In [66]:
named_tuple = (a = 1.2, b = 2, c = "hello")

(a = 1.2, b = 2, c = "hello")

The elements of the tuple can now be accessed using the names (in addition to the indexes) of the fields

In [67]:
named_tuple.b

2

When assigning values *from* a tuple, Julia supports some destructuring

In [68]:
x, y, z = tuple
y

2

This is useful when a function returns multiple outputs as a tuple

## Functions

### Named functions

Functions can be defined via the ```function``` keyword and terminated by ```end```:

In [69]:
function add_one_v1(x)
    return x + 1
end

add_one_v1 (generic function with 1 method)

The ```return``` keyword is not essential, the last value in the function is the one returned

In [70]:
function add_one_v2(x)
    x + 1
end

add_one_v2 (generic function with 1 method)

Simple functions can be defined in a single line without using the ```function``` keyword

In [71]:
add_one_v3(x) = x + 1

add_one_v3 (generic function with 1 method)

Functions can also return multiple values as a tuple

In [72]:
function add_and_mul(x, y)
    x + y, x * y
end

add_and_mul (generic function with 1 method)

In [73]:
a, m = add_and_mul(3, 4)

(7, 12)

#### Keyword arguments

Keyword arguments can be added after a semicolon in the argument list with a default value (in this case they are not mandatory) or without (in this case they are mandatory)

In [74]:
function add_constant(x; constant = 0)
    x + constant
end

add_constant (generic function with 1 method)

In [75]:
add_constant(3)


3

Functions can have a variable number of arguments. You can use ```...``` following a variable name to collect the remaining arguments in an array.

In [76]:
function varargs(x...)
    sum(x)
end

varargs (generic function with 1 method)

In [77]:
varargs(1,2,3,4,5,6)

21

### Anonymous (lambda) functions

Sometimes it is useful to define a function without giving it a name. We can use anonymous (lambda) functions

In [78]:
(x,y) -> x^2 + y^2

#24 (generic function with 1 method)

Functions can be assigned to variables and called like "normal" functions

In [79]:
ff = (x,y) -> x^2 + y^2
ff(2, 3)

13

In [80]:
typeof(ff)

var"#27#28"

### Broadcasting functions

Function call is among the operations that can be braodcasted using ```.```:

In [81]:
ff([1,2,3], [4,5,6]) # This gives an error

MethodError: MethodError: no method matching ^(::Vector{Int64}, ::Int64)
The function `^` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  ^(!Matched::Irrational{:ℯ}, ::Integer)
   @ Base mathconstants.jl:139
  ^(!Matched::Irrational{:ℯ}, ::Number)
   @ Base mathconstants.jl:139
  ^(!Matched::BigInt, ::Integer)
   @ Base gmp.jl:655
  ...


In [82]:
ff.([1,2,3], [4,5,6])

3-element Vector{Int64}:
 17
 29
 45

Since also the normal arithmetical operations are functions, they too can be broadcasted:

In [83]:
[1,2,3,4] .+ 1

4-element Vector{Int64}:
 2
 3
 4
 5

## Selection and Iteration

### Selection: ```if```, ```if```..```else```

Selection is performed, as usual, with the ```if``` construct

In [ ]:
x = 2
if x < 3
    println("x is less than 3")
end

Multiple conditions can be checked by combining them in a C-like way

In [ ]:
if x < 3 && x % 2 == 0
    println("x even and less than 3")
end

As usual, an ```if``` statement can include an ```else``` part

In [ ]:
if x < 3
    println("x is less than 3")
else
    println("x is at least 3")
end

Multiple ```if``` statements can be nested with ```elseif```

In [ ]:
if x < 3
    println("x is less than 3")
elseif x == 3
    println("x is exactly 3")
else
    println("x is more than 3")
end

### Iteration: ```for``` and ```while```

Iteration has the usual ```for``` and ```while``` constructs

In [ ]:
x = 1
while x ≤ 3
    println(x)
    x += 1
end

The ```for``` construct operates similarly to the ```for``` in Python. This means that we usually have ```for variable in container```.

In [ ]:
for v in 1:5
    println(v)
end

In [ ]:
typeof(1:5)

It is actually possible to use $\in$ instead of ```in```

In [ ]:
for v ∈ [1,2,3]
    println(v)
end

### Functional constructs

Some common operations can better be expressed as functional constructs (e.g., ```map```, ```filter```) or array comprehension instead of using loops directly

```map``` applies a _unary_ function to all the elements of a container

In [84]:
map(x -> x^2 + x, [1,2,3,4,5])

5-element Vector{Int64}:
  2
  6
 12
 20
 30

```reduce``` applies a _binary_ function to all elements of a container "merging" them in a single value

In [85]:
v = [4,5,6,7,3]
reduce(+, v)

25

Some kinds of reductions are so common that they have special functions defined

In [ ]:
minimum(v)

In [ ]:
maximum(v)

In [ ]:
sum(v)

In [ ]:
prod(v)

Another common operation is to filter a collection taking only the elements respecting a certain condition

In [ ]:
filter(x -> x ≥ 5, v)

Many complex operations can be carried by combining filtering, mapping, and reducting.

For example, let us compute the sum of the square of all the positive values inside a vector

In [ ]:
v = rand(10) .- 0.5

In [ ]:
v1 = filter(x -> x ≥ 0, v)
v2 = map(x -> x^2, v1)
v3 = sum(v2)

This application of functions where the output of one goes as input to the next is so common that a special idiom using ```|>``` exists. Similar operators exist, for example, in R and Clojure.

In [ ]:
filter(x -> x ≥ 0, v) |> x -> x.^2 |> sum

In [ ]:
v |> x -> x[x .≥ 0] |> x -> x.^2 |> sum

In general the form ```x |> f``` applies ```f``` to ```x```, so ```x |> f |> g |> h``` is ```h(g(f(x)))```

## Types

Until now we have not investigated how types can be useful for functions. We will start by defining how type annotations works

Some types: ```Float64```, ```Rational```, ```Int64```, ```Number```, ```Real```, etc. The types have a hierarchy: for example ```Number``` includes all numeric types, while ```Real``` all real numbers, and so on.

In [86]:
function f_only_reals(x::Real, y::Real)
    x + y
end

f_only_reals (generic function with 1 method)

Now a call like this works:

In [87]:
f_only_reals(3.5,4.0)

7.5

While using a string will give an error

In [88]:
f_only_reals("hello",  "world") # This gives an error

MethodError: MethodError: no method matching f_only_reals(::String, ::String)
The function `f_only_reals` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  f_only_reals(!Matched::Real, !Matched::Real)
   @ Main ~/Scrivania/progravanzata/julia/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y363sZmlsZQ==.jl:1


We can also annotate variables to force them to only contains values of a specific type

In [89]:
function g(x, y)
    v::Array{Int64,1} = [x,y]
    sum(v)
end

g (generic function with 1 method)

In [90]:
g(1,4)

5

Notice that some types have a parameter enclosed in curly brackets, like ```Array{Int64,1}``` or ```Rational{Int64}```.

They are type parameters, they have some similarities to templates in C++ or generics in Java.

It is possible to define union of types. For example if a parameter can be either a ```Float64``` or ```Int32``` we can define:

In [91]:
Union{Float64, Int32}

Union{Float64, Int32}

A useful type to define missing values is the ```Missing``` type, whose only value is ```missing```.

For example to define a function that accepts a one-dimensional array of ```Float64``` values or missing values we can define it using a union.

In [92]:
function f_missing(v::Array{Union{Float64,Missing},1})
    filter(x -> !ismissing(x), v) |> sum
end

f_missing (generic function with 1 method)

In [ ]:
f_missing([3.5, missing, 5, 8, missing, -3])

In [ ]:
missing + 4

### Structures

We can define new (product) types by defining structures:

In [93]:
struct MyPair
    first
    second
end

We have now defined a new type (```MyComplex```) that can be instantiated and used as a "normal" type:

In [94]:
c = MyPair(3, 5)

MyPair(3, 5)

In [95]:
typeof(c)

MyPair

We can access the different fields by using the dot notation:

In [96]:
c.first

3

Notice that we **cannot** modify a struct, since by default they are _immutable_:

In [97]:
c.second = 4 # this gives an error

ErrorException: setfield!: immutable struct of type MyPair cannot be changed

If we really need a _mutable_ structure we must define it so

In [98]:
mutable struct MyMutablePair
    first
    second
end

In [100]:
p = MyMutablePair(4, 7)

MyMutablePair(4, 7)

In [ ]:
p.second = 8

In [ ]:
p

We can define a "template" structure by using a type parameter

In [ ]:
struct MySameTypePair{T}
    first::T
    second::T
end

In [ ]:
MySameTypePair(3,4)

In [ ]:
MySameTypePair{String}("Hello", "World")

In [ ]:
MySameTypePair(2, 3.4) # This gives an error

Fields of a structure can be typed independently.

In [9]:
struct MyPairV2
    first::String
    second::Float64
end

## Multiple Dispatch

Why are types useful? 

- They provide a way to give an error if the type in the annotation is not respected
- They can be used for dispatch! (see [The Unreasonable Effectiveness of Multiple Dispatch by Stefan Karpinski](https://www.youtube.com/watch?v=kc9HwsxE1OY))

Until now we have defined a function only once, we might want to define it multiple times depending on the types of the parameters 

In [101]:
function h(x::Float64, y::Float64)
    println("x and y are float")
end

function h(x::Float64, y::Int64)
    println("x is float and y is integer")
end

function h(x::Int64, y::Float64)
    println("x is integer and y is float")
end

function h(x::Int64, y::Int64)
    println("x and y are integer")
end

h (generic function with 4 methods)

In [102]:
h(3.4, 2)
h(3, 2.7)

x is float and y is integer
x is integer and y is float


We can see how many _methods_ every function has:

In [ ]:
methods(h)

We can see it even for built-in functions

In [ ]:
methods(+)

Why is multiple dispatch useful?

We can write a function using, for example, ```+``` and the correct implementation will be the one used.

For example we can write a function working with matrix multiplication and the correct implementation (depending if the matrix is, for example, diagonal, tridiagonal, etc) will be used.

## Environments and Packages

It is essential to be able to create multiple environments, each one with a different set of packages installed and to make the environment reproducible across multiple machines.

We can either work directly with the ```Pkg``` package (you can import it with ```using Pkg```) or on the REPL by going into the package management with ```]```

 - ```activate``` allows to create a (or activate an existing) new self-contained project. All installs will be local to the project. The ```Manifest.toml``` and ```Project.toml``` files contains the information about the installed packages and their versions
 - ```add package_name``` install the package, resolving the dependencies. For example, ```add IJulia``` to have a notebook interface.
 - ```rm package_name``` to remove a package from the current project
 - ```update``` to update the packages

All code that we will see in the course can be installed as packages or it is in the base library.

## Macros

Macros are a tool for _metaprogramming_. That is, for writing code that writes code. They are well known in the Lisp word and are gaining popularity in other languages.

Recall that the arguments of a function are evaluated before being passed to a function.

Arguments to a macro are not evaluated. The macro receives the (representation of the) code and can manipulate it returning new code.

Macro should not be used too estensively, but they are a powerful tool. In Julia they always have ```@``` before their name

#### Some useful macros

The ```@time``` macro allows to find the amount of time spent in executing a piece of code

In [ ]:
@time map(x->x^2, rand(1000));

It is possible to explore which method of a function Julia is going to call using the ```@which``` macro

In [ ]:
@which 3 + 5

It is actually possible to observe which is the code generate by Julia with a collection of macros ```@code_lowered```, ```@code_typed```, ```@code_llvm```, ```@code_native```

In [103]:
@code_lowered 3 + 5

CodeInfo(
1 ─ %1 = Base.add_int
│   %2 =   dynamic (%1)(x, y)
└──      return %2
)

In [104]:
@code_typed 3 + 5

CodeInfo(
1 ─ %1 = intrinsic Base.add_int(x, y)::Int64
└──      return %1
) => Int64

In [105]:
@code_llvm 3 + 5

; Function Signature: +(Int64, Int64)
;  @ int.jl:87 within `+`
define i64 @"julia_+_11845"(i64 signext %"x::Int64", i64 signext %"y::Int64") #0 {
top:
  %0 = add i64 %"y::Int64", %"x::Int64"
  ret i64 %0
}


In [106]:
@code_native 2 + 3

	.text
	.file	"+"
	.section	.ltext,"axl",@progbits
	.globl	"julia_+_11956"                 # -- Begin function julia_+_11956
	.p2align	4, 0x90
	.type	"julia_+_11956",@function
"julia_+_11956":                        # @"julia_+_11956"
; Function Signature: +(Int64, Int64)
; ┌ @ int.jl:87 within `+`
# %bb.0:                                # %top
	#DEBUG_VALUE: +:x <- $rdi
	#DEBUG_VALUE: +:y <- $rsi
	push	rbp
	mov	rbp, rsp
	lea	rax, [rdi + rsi]
	pop	rbp
	ret
.Lfunc_end0:
	.size	"julia_+_11956", .Lfunc_end0-"julia_+_11956"
; └
                                        # -- End function
	.section	".note.GNU-stack","",@progbits


We can see how a macro acts on the code via ```@macroexpand```

In [ ]:
@macroexpand @timed 3 + 5

Macros are one of the features that allows Julia to be flexible.

#### Code representation

Can can be forced not be evaluated by putting it in a ```quote``` block or by using the ```:``` operator

In [ ]:
code1 = quote
    x = 4
    y = 6
    x + y
end

code2 = :(3 + 5)
code1

We can manipulate code as data (a concept that should be familiar to programmers in the lisp family of languages)

In [ ]:
typeof(code2)

In [ ]:
Meta.show_sexpr(code2)

In [ ]:
code2.head

In [ ]:
code2.args

The code starts with a function call (```:call```) where the function is ```+``` and the arguments are ```3``` and ```5```.

We can modify the code directly

In [ ]:
code2.args[1] = :* # We modify the function from + to *

In [ ]:
code2

In [ ]:
eval(code2)

## Linear Algebra

Let see some common linear algebra operations.

We generate some random matrices and vectors

In [ ]:
A = rand(3, 3) # Random 3 by 3 matrix

In [ ]:
b = rand(3) # random vector of three elements

The ```\``` operator solves the linear system $Ax = b$.

In [ ]:
x = A\b

Matrix multiplication, addition, etc. are already possible via multiple dispatch using the same operators used for numbers

In [ ]:
A*b

In [ ]:
A^3

In [ ]:
b * transpose(b)

Notice that all operation like ```reduce```, ```prod```, ```sum``` works on arrays of matrices as well. 

In [ ]:
sum([rand(2,2) for i in 1:5])

In [ ]:
prod([rand(2,2) for i in 1:5])

We can use more linear algebra functions by importing the module ```LinearAlgebra```

In [ ]:
using LinearAlgebra

We have now access to code for findig eigenvalues and eigenvectors

In [ ]:
A = [1 0 2
     3 4 8
     0 0 7]

eigen(A)

Or to compute, for example, the SVD

In [ ]:
svd(A)

But how many methods do we have to compute the SVD?

In [ ]:
methods(svd)

Let us create a _diagonal_ matrix:

In [ ]:
D = Diagonal([1.,5.,9.])

We can still call the ```svd``` function and the correct implementation will be called 

In [ ]:
svd(D)

In [ ]:
@which svd(D)

We have many different kinds of matrices

In [ ]:
T = LowerTriangular(A)

In [ ]:
svd(T)

In [ ]:
@which svd(T)

This allows to write the same code and have it compile down to the correct (and optimized) implementation

### The end

The following is valid Julia code:

In [114]:
for a in '🌑':'🌘'
    print(a)
end

🌑🌒🌓🌔🌕🌖🌗🌘

## Extras

#### Custom ```+``` for string concatenation

Let us add ```+``` as string concatenation. We start by importing ```Base:+```

In [108]:
import Base:+

We define how ```+``` should work with strings

In [109]:
function +(x::String, y::String)
    x * y
end

+ (generic function with 192 methods)

In [110]:
"Hello " + "World"

"Hello World"

And now functions written **before** we wrote our ```+``` implementation will make use of it.

In [111]:
sum(["Hello", " ", "world"])

"Hello world"

#### A ```@unless``` macro

We want to write a macro that execute a piece of code _unless_ a certain condition is satisfied

In [ ]:
macro unless(test, body)
    quote
        if !$test
            $body
        end
    end
end

In [ ]:
x = 4
@unless x ∈ 1:5 println("Foo")
@unless x > 10 println("Bar")

In [ ]:
@macroexpand @unless x ∈ 1:5 println("Foo")

#### Push!, Sort!, and functions modifying their arguments

Some functions modify their arguments. By convention such functions are denoted by a ```!``` at the end of the name.

For example ```push!``` and ```pop!``` can be used to add and remove elements at the end of an array

In [ ]:
v = [1,2,3,4]
push!(v, 5)
v

In [ ]:
pop!(v)
v

Some functions have two versions. Like ```sort```, returning a sorted copy of the original array, and ```sort!```, sorting the array passed as argument directly.

In [ ]:
w = rand(10)

In [ ]:
sort(w)

In [ ]:
w

In [ ]:
sort!(w)

In [ ]:
w